# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 2ef1de52fa20310312f39118e7714af6b86a216714bef06210ef2d865f4964c1610ea4b6e940fad0fefba5760a91d40c425ec387d47790bc8fdb43b2d80542a6

test:
  domain_name: example.com 
  secret_key_base: 90ad197a562d31dbe0f234971092ead3d437bea3264a3e15ceb1680767f98439f1baa9ea83a70a193ece6b4c27a48ca2c878f40e7e8563e3e34d6457142b84c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
