development:
  admin_email: admin@test.de
  admin_password: admin123
  domain_name: test.de
  secret_key_base: 2ef1de52fa20310312f39118e7714af6b86a216714bef06210ef2d865f4964c1610ea4b6e940fad0fefba5760a91d40c425ec387d47790bc8fdb43b2d80542a6

test:
  domain_name: example.com
  secret_key_base: 90ad197a562d31dbe0f234971092ead3d437bea3264a3e15ceb1680767f98439f1baa9ea83a70a193ece6b4c27a48ca2c878f40e7e8563e3e34d6457142b84c4

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["EMAIL_USER"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD"] %>
